### ISSUE TITLE
when the chunk size is low, the sentence is being breaked abruptly

### ISSUE THREAD

**Issue by Ajaytherala** [gioelecrispo/chunkipy#5] opened 2024-09-05 19:14 UTC
![image](https://github.com/user-attachments/assets/01ebd366-1e1f-437b-9d9c-c3851bfe9652)

**Comment by gioelecrispo** [comment] 2024-09-05 21:59
Hello @Ajaytherala, thank you for using `chunkipy`.
The behaviour you are facing is **expected**. As you can see in the documentation, this is expected to happen if the sentence segmenter is unable to split the text into sentences that have less than `chunk_size` token.

From README.md:

> By default, `chunkipy` uses `stanza` are main text splitting method; however, if stanza produces sentences with a number of tokens greater than the chunk size, other split strategy are used. Here the list of predefined strategies, sorted by priority (the first one is executed first, if the piece of text is larger than the chunk size, it is further split using a lower priority strategy).


If this behaviour does not suit your needs, you can provide your own split strategies.
Closing as this is not a bug.

**Closed by gioelecrispo** 2024-09-05 21:59 UTC
